# Generated by Django 4.0 on 2022-03-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
